### ISSUE TITLE
Missfunctional links

### ISSUE THREAD

**Issue by luilver** [mmoya/msti-chatrpc#1]
### 404 Not found
- https://gsyc.urjc.es/master 

### Taking too long to respond
- http://docencia.etsit.urjc.es/moodle/file.php/100/Material_curso_2011_2012/Practicas/RPCs/introRPC.pdf (redirected from http://j.mp/zi7Hf1)

**Comment by mmoya** [comment]
Attached [introRPC.pdf](https://github.com/mmoya/msti-chatrpc/files/15436764/01.introRPC.pdf) that is in spanish. The master program closed and their site was removed. There is no working capture in the Wayback Machine although the department page is still alive at https://gsyc.urjc.es/ but seems unmaintained.
